export const config = {
    BACKEND_SERVICE_BASE_URL: process.env.REACT_APP_BACKEND_SERVICE_BASE_URL,
    LOGIN_URI: process.env.REACT_APP_LOGIN_URI,
    REGISTER_URI: process.env.REACT_APP_REGISTER_URI,
    ALL_USER_ROLES_URI: process.env.REACT_APP_ALL_USER_ROLES_URI,
    USER_DETAILS_URI: process.env.REACT_APP_USER_DETAILS_URI,
    REFRESH_TOKEN: process.env.REACT_APP_REFRESH_TOKEN,
    BACKEND_NOTIFICATION_SERVICE_BASE_URL: process.env.REACT_APP_BACKEND_NOTIFICATION_SERVICE_BASE_URL,
    NOTIFICATION_TEMPLATE_CREATE_URI: process.env.REACT_APP_NOTIFICATION_TEMPLATE_CREATE_URI,
    NOTIFICATION_TEMPLATE_FIND_ALL_URI: process.env.REACT_APP_NOTIFICATION_TEMPLATE_FIND_ALL,
};